version: "3.8"

services:
  backend:
    image: ${IMAGE_FULL_URL}
    container_name: ${DOCKERHUB_IMAGE_NAME}
    restart: always
    environment:
      - TZ=Asia/Seoul
    ports:
      - '8080:8080'
    env_file: .env