spring:
  application:
    name: wageul-server
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${PSQL_URL}
    username: ${PSQL_USERNAME}
    password: ${PSQL_PASSWORD}
  # jpa properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

#registration
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URL}
            authorization-code: ${GOOGLE_AUTH_CODE}
            scope: profile,email
            access-token-url: https://oauth2.googleapis.com/token
            profile-url: https://www.googleapis.com/userinfo/v2/me

  # jwt
  jwt:
    secret: ${JWT_SECRET}
    expire-length: 86400000

  client:
    url: http://localhost:3000
