package com.wageul.wageul_server.mock;

import com.wageul.wageul_server.experience.domain.Experience;
import com.wageul.wageul_server.experience.service.port.ExperienceRepository;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

public class FakeExperienceRepository implements ExperienceRepository {

    private Long autoGeneratedId = 0L;
    private final List<Experience> data = new ArrayList<>();

    @Override
    public List<Experience> findAll() {
        return data;
    }

    @Override
    public Experience save(Experience experience) {
        if(experience.getId() == 0) {
            Experience newExperience = Experience.builder()
                    .id(++autoGeneratedId)
                    .title(experience.getTitle())
                    .location(experience.getLocation())
                    .datetime(experience.getDatetime())
                    .content(experience.getContent())
                    .duration(experience.getDuration())
                    .cost(experience.getCost())
                    .contact(experience.getContact())
                    .limitMember(experience.getLimitMember())
                    .language(experience.getLanguage())
                    .createdAt(LocalDateTime.now())
                    .updatedAt(LocalDateTime.now())
                    .build();
            data.add(newExperience);
            return newExperience;
        } else {
            data.removeIf(item -> Objects.equals(item.getId(), experience.getId()));
            data.add(experience);
            return experience;
        }
    }
}
